version: "3.1"

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=complete-crud-spring-mvc
    ports:
      - "5433:5432"